apiVersion: v1
kind: Secret
metadata:
  name: kp-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kp.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: dev-retailpartnerx-change-me
  NEO4J_PASSWORD: {{ .Values.neo4j.password | quote }}
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
